@extends('layouts.public')

@section('title', 'Over ons | Sales en Marketing Vacatures')
@section('meta_description', 'Lees waarom Sales en Marketing Vacatures zich richt op relevante kansen, werkgevers en vakinhoud voor commerciële professionals.')
@section('canonical', route('about'))
@section('header_theme', 'dark')

@section('content')
    <section class="relative">
        <div class="absolute inset-0 -z-10 mb-48 bg-slate-900 lg:mb-0 lg:h-[30rem]" aria-hidden="true"><img class="h-full w-full object-cover opacity-10" src="{{ asset('images/about-hero.jpg') }}" width="1440" height="497" alt=""></div>
        <div class="relative mx-auto max-w-6xl px-4 sm:px-6"><div class="pt-32 md:pt-40"><div class="mx-auto max-w-3xl pb-16 text-center"><p class="mb-3 text-sm font-semibold uppercase tracking-widest text-blue-300">Over SMV</p><h1 class="h1 font-playfair-display text-slate-100">Een gespecialiseerd platform voor commerciële loopbanen</h1></div><div class="flex justify-center"><img class="mx-auto" src="{{ asset('images/about-intro.jpg') }}" width="1024" height="576" alt="Professionals in gesprek over samenwerken"></div></div></div>
    </section>
    <section class="-translate-y-1/2"><div class="mx-auto max-w-6xl px-4 sm:px-6"><div class="mx-auto max-w-3xl bg-blue-600 py-4 shadow-xl"><ul class="flex"><li class="w-1/3 px-2 text-center"><div class="font-playfair-display text-3xl font-bold text-white md:text-5xl">Sales</div><div class="mt-2 text-xs font-medium text-blue-200 sm:text-sm">Commercieel talent</div></li><li class="w-1/3 border-x border-blue-500 px-2 text-center"><div class="font-playfair-display text-3xl font-bold text-white md:text-5xl">Marketing</div><div class="mt-2 text-xs font-medium text-blue-200 sm:text-sm">Sterke merken</div></li><li class="w-1/3 px-2 text-center"><div class="font-playfair-display text-3xl font-bold text-white md:text-5xl">Groei</div><div class="mt-2 text-xs font-medium text-blue-200 sm:text-sm">Volgende stap</div></li></ul></div></div></section>
    <section><div class="mx-auto max-w-3xl px-4 pb-16 text-lg leading-8 text-slate-500 sm:px-6 md:pb-24"><h2 class="mb-4 font-playfair-display text-3xl text-slate-800">Waarom SMV bestaat</h2><p class="mb-6">Wie op een algemeen vacatureplatform zoekt, moet vaak eerst veel andere functies wegfilteren. Sales en Marketing Vacatures brengt daarom vacatures, werkgevers en vakinhoud binnen één herkenbaar werkgebied samen.</p><p class="mb-6">Het platform bestaat al langere tijd en heeft door de jaren heen verschillende werkgevers en professionals met elkaar in contact gebracht. Sinds de recente overname krijgt SMV opnieuw gerichte aandacht en wordt het platform stap voor stap verder ontwikkeld.</p><p>We kiezen daarbij voor heldere vacature-informatie, ruimte voor verschillende loopbaanfasen en content die professionals helpt zich in sales en marketing te blijven ontwikkelen.</p><div class="mt-8"><a class="font-semibold text-blue-700 transition hover:text-blue-800 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-blue-600" href="{{ route('contact') }}">Neem contact op <span aria-hidden="true">→</span></a></div></div></section>
@endsection
